//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selling
    {
        public int IDS { get; set; }
        public Nullable<int> IDCUS { get; set; }
        public Nullable<int> IDCOM { get; set; }
        public Nullable<int> Quality { get; set; }
        public Nullable<int> Price { get; set; }
        public string DateOfSale { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
