//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentTypes
    {
        public ComponentTypes()
        {
            this.Components = new HashSet<Components>();
        }
    
        public int IdComponentType { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Components> Components { get; set; }
    }
}
