//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Components
    {
        public Components()
        {
            this.Receipts = new HashSet<Receipts>();
        }
    
        public int IDCOM { get; set; }
        public Nullable<int> Type { get; set; }
        public string Nazv { get; set; }
        public string Description { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual ComponentTypes ComponentTypes { get; set; }
        public virtual ICollection<Receipts> Receipts { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
