//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            this.Assembly = new HashSet<Assembly>();
            this.Selling = new HashSet<Selling>();
        }
    
        public int IdCustomer { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public string Authority { get; set; }
        public string Address { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
    
        public virtual ICollection<Assembly> Assembly { get; set; }
        public virtual ICollection<Selling> Selling { get; set; }
    }
}
