//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipts
    {
        public int IDR { get; set; }
        public Nullable<int> IDSUP { get; set; }
        public Nullable<int> IDCOM { get; set; }
        public Nullable<int> Quality { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
    
        public virtual Components Components { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
