//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public Suppliers()
        {
            this.Receipts = new HashSet<Receipts>();
        }
    
        public int IDSUP { get; set; }
        public string FIO { get; set; }
        public string Firm { get; set; }
        public string Position { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
    
        public virtual ICollection<Receipts> Receipts { get; set; }
    }
}
